using Microsoft.AspNetCore.Components;

namespace FeedbackWebApp.Services;

/// <summary>
/// Service to access the CSP nonce from the current HTTP context for use in Blazor components.
/// The nonce is generated by SecurityHeadersMiddleware and stored in HttpContext.Items.
/// </summary>
public interface ICspNonceService
{
    /// <summary>
    /// Gets the current CSP nonce for this request, or an empty string if not available.
    /// </summary>
    string GetNonce();
}

public class CspNonceService : ICspNonceService
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public CspNonceService(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public string GetNonce()
    {
        var httpContext = _httpContextAccessor.HttpContext;
        if (httpContext?.Items.TryGetValue("csp-nonce", out var nonce) == true)
        {
            return nonce?.ToString() ?? string.Empty;
        }
        return string.Empty;
    }
}
