name: Build and Publish Local MCP Container

on:
  push:
    branches: [ main ]
    paths:
      - 'FeedbackFlow.MCP.Local/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'FeedbackFlow.MCP.Local/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build FeedbackFlow.MCP.Local
        run: dotnet build FeedbackFlow.MCP.Local/FeedbackFlow.MCP.Local.csproj

  build-and-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish FeedbackFlow.MCP.Local as Container
        run: dotnet publish FeedbackFlow.MCP.Local/FeedbackFlow.MCP.Local.csproj /t:PublishContainer -p ContainerRegistry=docker.io