name: Build and Publish FeedbackFlowLocalMCP Container

on:
  push:
    branches: [ main ]
    paths:
      - 'FeedbackFlowLocalMCP/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'FeedbackFlowLocalMCP/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build FeedbackFlowLocalMCP
        run: dotnet build FeedbackFlowLocalMCP/FeedbackFlowLocalMCP.csproj

  build-and-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish FeedbackFlowLocalMCP as Container
        run: dotnet publish FeedbackFlowLocalMCP/FeedbackFlowLocalMCP.csproj /t:PublishContainer -p ContainerRegistry=docker.io